### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by bachya** [FuzzyMistborn/python-eufy-security#10]
We're in a good spot to release [0.0.1](https://github.com/FuzzyMistborn/python-eufy-security/releases/tag/0.0.1) to PyPI. Waiting on @FuzzyMistborn to ensure he has an account (so that he can be added as a maintainer).

**Comment by bachya** [comment]
Went ahead and added a `setup.py` (3cb5cf1f8114) and published to PyPI (https://pypi.org/project/python-eufy-security/). All that's left is to add you as a maintainer, @FuzzyMistborn; let me know when you have your PyPI username.

**Comment by FuzzyMistborn** [comment]
Yes I do, @fuzzymistborn is the name.  Thanks for setting it up.  Close once you add me.

**Comment by bachya** [comment]
Done!
