### ISSUE TITLE
Users outside of the US don't see their cameras

### ISSUE THREAD

**Issue by nonsleepr** [FuzzyMistborn/python-eufy-security#15]
See nonsleepr/ha-eufy-security#2 for details.

Here's the list of possible domains from the Android app:

- security-app.eufylife.com (default/US)
- security-app-eu.eufylife.com (EU)
- security-app-pr.eufylife.com (PR)

- security-app-ci.eufylife.com (is that continuous integration?)
- security-app-qa.eufylife.com (quality assurance?)
- security-app-sqa.eufylife.com (short quality assurance)

**Comment by alesoft73** [comment]
Yes, i came from Italy.
I can't connect.

**Comment by bachya** [comment]
Closing as fixed by #20.
