### ISSUE TITLE
Support for Security Motion Sensors

### ISSUE THREAD

**Issue by bachoo786** [FuzzyMistborn/python-eufy-security#48]
**Is your feature request related to a problem? Please describe.**
Is it possible that the security motion and entry sensors be integrated within this python eufy security library please?

**Comment by air720boarder** [comment]
Adding to this. Any plans to incorporate motion alerts?

**Comment by BergenLarsen** [comment]
Happy to help out with testing - have device...  DM me for contact info.

**Comment by alanhamlett** [comment]
Related to #52.
