### ISSUE TITLE
Easy script to put camera night vision on / off for home bridge

### ISSUE THREAD

**Issue by martinorob** [FuzzyMistborn/python-eufy-security#51]
Hi, 
I need simple example script to turn on and off the night vision of my Eufy indoor cam.
The example script works well but I don't know how I can add the code to turn on and off night vision.

Please give me some example.

Thanks!

**Comment by FuzzyMistborn** [comment]
Not really a library question.  May be better off posting in the forum: https://community.home-assistant.io/t/eufy-camera-integration/121758/238
