### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by FuzzyMistborn** [FuzzyMistborn/python-eufy-security#6]

**Comment by FuzzyMistborn** [comment]
Will need to note that user needs to create a second account in order to use.  Eufy only permits one session per user so if the user's "main" account is used it will log the user out of the phone and vice versa.  User should be directed to create a second account and share.

**Comment by rpitera** [comment]
This is similar to how the Arlo integration works, so you should be able to refer to the wording on their setup.  Really excited about the progress here; I'm about to receive a eufyCam 2 Security System from Best Buy to review so once I get them set up, I'd be interested in beta testing .
