### ISSUE TITLE
Status of repo

### ISSUE THREAD

**Issue by FuzzyMistborn** [FuzzyMistborn/python-eufy-security#61]
Just in case people miss it in the Readme, going to sticky this to the top.

# **:rotating_light: THIS LIBRARY IS CURRENTLY UNMAINTAINED :rotating_light:** 

You can open issues, but do not expect them to get answered/fixed.

I plan to archive this repo in a couple of months.

**Comment by iantrich** [comment]
I'd recommend transferring ownership to the custom_components project

**Comment by FuzzyMistborn** [comment]
Naw, this is the client library and it's basically non-functional at this point.  There's a better library now.

**Comment by evilmarty** [comment]
I just wanted to let you know that I've appreciated all the work that you've done @FuzzyMistborn. I've expanded from it, and @keshavdv's work done in #44, to add more device support and better integration with [HA](https://home-assistant.io).

If you are interested, please check out https://github.com/evilmarty/python-eufy-security and https://github.com/evilmarty/ha-eufy-security.

I am also interested in becoming this project maintainer if that is a possibility.

**Comment by FuzzyMistborn** [comment]
Awesome that you're continuing to work on this.  Bropat just realized a websocket version of his eufy library [here](https://github.com/bropat/eufy-security-ws) that I think Bachya was thinking to use.  But if you want to continue improving my library I'm more than willing to give you commit rights to the repo.

**Comment by evilmarty** [comment]
@FuzzyMistborn if you don't mind, I'm eager to continue working on this to improve HA support for Eufy Security devices.

**Comment by FuzzyMistborn** [comment]
Nope, no problem.  Sent you an invite to be a collaborator.  Let me know if you need anything.

**Comment by evilmarty** [comment]
I'm going to tackle any issues that are raised and continue with the maintenance and advancement of this library. Please reach out if you have any questions.
