### ISSUE TITLE
Device type enumeration is stale

### ISSUE THREAD

**Issue by GWustenstein** [FuzzyMistborn/python-eufy-security#71]
**Describe the bug**
device_type enumeration appears to be stale, Eufy has released a number of new devices and types since this module was last updated.

I found this, oddly, because the example code iterates through devices as if they all are cameras, thinking the driver was 'smart' and the type code was being invoked 'under the hood' for something magic in the class that indicated to the API this was specific for cameras (apparently eufy calls pretty much anything a 'camera', lol!).  Looking deeper, there's no magic, so the example crashes if there is a device returned in the list (such as a sensor) and it tries to retrieve an image URL for such an object.  Then I went, 'hey, what version got installed by pip?' and it was even older than this repo.

So... I guess the readme needs a short update to suggest install from git, along with updated enumerations, and there's that note about 'deprecated is_camera' property that is used in the example anyways

**Comment by FuzzyMistborn** [comment]
At this point this library is deprecated/unmaintained.  I suggest using something like bropat's eufy-security client instead.

**Comment by GWustenstein** [comment]
That's node.js, not python correct?

**Comment by FuzzyMistborn** [comment]
Yes.  But you can look at https://github.com/bachya/eufy-security-ws-python as an example of how to wrap it up in Python.

**Comment by GWustenstein** [comment]
Well, I guess it's time to suit up and learn A New Thing...
