### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by bachya** [FuzzyMistborn/python-eufy-security#9]
We should set up continuous integration through Travis CI so that as the library grows, we can ensure that it builds correctly, continues to pass the test suite, etc.

@FuzzyMistborn I can do the work inside the repo, but I will need you to set up the integration with Travis CI. I've done this before, so let me know if you need help.

**Comment by FuzzyMistborn** [comment]
Sorry to not get around to this before now, life got busy.  I've never set up Travis CI, so could definitely use help when you can.

**Comment by bachya** [comment]
No worries! This isn't a huge rush. Will put on my todo list.

**Comment by bachya** [comment]
I recently transitioned all of my libraries to GitHub Actions instead of TravisCI (faster, local to GitHub, easier to manage, etc.). Just an FYI; going to implement the same thing here.

**Comment by FuzzyMistborn** [comment]
Works for me.

**Comment by bachya** [comment]
Haven’t actually done the work yet, so let’s keep this open.

**Comment by bachya** [comment]
@FuzzyMistborn One assist I could use:

1. Log into https://codecov.io/ with your GitHub account.
2. Add this repository.
3. Go into the repo settings and send me the `Repository Upload Token` (don't post it here).

Thanks!

**Comment by FuzzyMistborn** [comment]
PM sent on HASS forum

**Comment by bachya** [comment]
Implemented via #22, but first run failed (https://github.com/FuzzyMistborn/python-eufy-security/commit/8a9ba7a2e5a70a8cc390cfc02d44164ef1c5d452/checks?check_suite_id=355441118) – going to keep this issue open until I can fix it.
